### ISSUE TITLE
[fhir-server-exporter] Container fails to start in current chart version 1.0.7

### ISSUE THREAD

**Issue by bauerjs1** [chgl/charts#262]
Hi,

Just to note, with current chart version 1.0.7 the container crashes with
```
Failed to create CoreCLR, HRESULT: 0x80070008
```

We don't have this behavior in 1.0.6 and earlier. I suspect a bug in the .NET base image, maybe this is a temporary one.

Cheers!

**Comment by chgl** [comment]
Sorry about that! Most likely due to https://docs.linuxserver.io/faq#jammy since the new image is based on ubuntu jammy. The second workaround *might* be equivalent to setting https://github.com/chgl/charts/blob/master/charts/fhir-server-exporter/values.yaml#L56 to {}. ie 

```yaml
securityContext:
  seccompProfile: {}
```

If the issue persists I could also revert the use of a new jammy-base image until it is more widely adopted.

The chart has been automatically tested on kind k8s 1.22, 23, 24 running on ubuntu 22.04 so the error might not have been caught on CI.

**Comment by chgl** [comment]
I've tested it with an older version of kind 0.11.0, which uses containerd 1.5 and can reproduce the issue. Upgrading containerd to 1.6 should do the trick. The root-cause/fix is https://github.com/containerd/containerd/pull/5982/commits/55923daa9f56c8a890875f1e111201d918b382e2
